source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'ZFCycleScrollViewExample' do
  
  pod 'Reveal-SDK',                   '~> 4'
  pod 'ZFCycleScrollView',            :path => '../ZFCycleScrollView.podspec'
  
end

